### ISSUE TITLE
Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by shuliangfu** [kawanet/express-intercept#2]
Cannot set headers after they are sent to the client
How to deal with this error? Thank you！

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:536:11)
    at ResponsePayload.setBuffer (/Users/shuliangfu/worker/node/chain/node_modules/express-intercept/lib/_payload.js:73:17)
    at ResponsePayload.setString (/Users/shuliangfu/worker/node/chain/node_modules/express-intercept/lib/_payload.js:104:14)
    at /Users/shuliangfu/worker/node/chain/node_modules/express-intercept/lib/express-intercept.js:59:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async finish (/Users/shuliangfu/worker/node/chain/node_modules/express-intercept/lib/_handler.js:73:67) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
(node:4348) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:536:11)
    at ServerResponse.header (/Users/shuliangfu/worker/node/chain/node_modules/express/lib/response.js:771:10)
    at ServerResponse.header (/Users/shuliangfu/worker/node/chain/node_modules/express/lib/response.js:774:12)
    at defaultErrorHandler (/Users/shuliangfu/worker/node/chain/node_modules/express-intercept/lib/express-intercept.js:17:21)
    at sendError (/Users/shuliangfu/worker/node/chain/node_modules/express-intercept/lib/_handler.js:78:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kawanet** [comment]
> Cannot set headers after they are sent to the client

Right. It's impossible to rewrite headers if an upstream middleware has started to send some of headers before `responseHandler` handle it. Some middlewares would kick a signal for Express to start to send response header. Try to change the order to load middlewares.

**Comment by shuliangfu** [comment]
The problem is resolved, thank you very much
